### ISSUE TITLE
Regex challenge

### ISSUE THREAD

**Issue by Brendan-csel** [amoutonbrady/esbuild-plugin-solid#2]
Thanks for putting this together.

I think there is a small issue with the regex that tests if the file contains any JSX.  

``` js
var JSX_RE = /<.+?>/gim;
```
apparently the (g)lobal flag causes the regex to [remember state between calls](https://stackoverflow.com/questions/2851308/why-does-my-javascript-regex-test-give-alternating-results).  This was causing my build to intermittently try to feed a .tsx file into the .ts loader - which makes it unhappy.

Given we probably only care about finding one set of <...> perhaps the global flag can be removed?

**Comment by Brendan-csel** [comment]
Possibly the "i" (case insensitive) flag doesn't really add much either.

**Comment by Brendan-csel** [comment]
After further testing I think this inner regex check may need to go altogether and always process .jsx or .tsx files based on their name only. 

The regex shown above also doesn't work if there are no opening and closing angle brackets on the same line ...and it matches typescript functions like Omit<...>. 

I'll put a pull request shortly.

**Comment by amoutonbrady** [comment]
Fixed via #3

**Comment by amoutonbrady** [comment]
Published in 0.3.1
